server:
  port: 8084
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true 

spring:
  config:
    import:
    - optional:configserver:http://localhost:8085
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
            - Path=/user/**
          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
            - Path=/hotel/**
            
          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
            - Path=/rating/**
