

server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root 
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - optional:configserver:http://localhost:8085

# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#   instance:
#     prefer-ip-address: true


    